language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install -U setuptools
script:
  - python setup.py test
  - python setup.py flake8
after_success:
  - coveralls
  - codecov
